[2025-04-29T18:24:48.691-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: opportunity_pipeline.ingest_eventbrite scheduled__2025-04-29T20:00:00+00:00 [queued]>
[2025-04-29T18:24:48.696-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: opportunity_pipeline.ingest_eventbrite scheduled__2025-04-29T20:00:00+00:00 [queued]>
[2025-04-29T18:24:48.696-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-29T18:24:48.696-0400] {taskinstance.py:1280} INFO - Starting attempt 3 of 2
[2025-04-29T18:24:48.696-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-29T18:24:48.700-0400] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_eventbrite> on 2025-04-29 20:00:00+00:00
[2025-04-29T18:24:48.704-0400] {standard_task_runner.py:55} INFO - Started process 40724 to run task
[2025-04-29T18:24:48.707-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'opportunity_pipeline', 'ingest_eventbrite', 'scheduled__2025-04-29T20:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/opportunity_ingest_dag.py', '--cfg-path', '/var/folders/bc/zt35hlqn755d7y9zj64rxxph0000gn/T/tmpsepewa39']
[2025-04-29T18:24:48.711-0400] {standard_task_runner.py:83} INFO - Job 10: Subtask ingest_eventbrite
[2025-04-29T18:24:48.754-0400] {task_command.py:388} INFO - Running <TaskInstance: opportunity_pipeline.ingest_eventbrite scheduled__2025-04-29T20:00:00+00:00 [running]> on host zihaos-macbook-pro.local
[2025-04-29T18:24:48.780-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=opportunity_pipeline
AIRFLOW_CTX_TASK_ID=ingest_eventbrite
AIRFLOW_CTX_EXECUTION_DATE=2025-04-29T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-29T20:00:00+00:00
[2025-04-29T18:31:57.136-0400] {local_task_job.py:255} WARNING - Recorded pid 41954 does not match the current pid 40724
[2025-04-29T18:31:57.177-0400] {process_utils.py:129} INFO - Sending 15 to group 40724. PIDs of all processes in the group: [40724]
[2025-04-29T18:31:57.178-0400] {process_utils.py:84} INFO - Sending the signal 15 to group 40724
[2025-04-29T18:32:57.206-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=40724, name='Python', status='running', started='18:24:48') did not respond to SIGTERM. Trying SIGKILL
[2025-04-29T18:32:57.226-0400] {process_utils.py:84} INFO - Sending the signal 9 to group 40724
[2025-04-29T18:32:57.245-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=40724, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:24:48') (40724) terminated with exit code -9
[2025-04-29T18:32:57.253-0400] {standard_task_runner.py:168} ERROR - Job 12 was killed before it finished (likely due to running out of memory)
